version: '3'
services:
  develop:
    build:
      context: .
      dockerfile: ./Dockerfile.dockerfile
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
      - /app/node_modules
    command:
      - npm
      - run
      - serve
    environment: 
      - CHOKIDAR_USEPOLLING=true
